language: cpp
compiler: gcc

os: linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10

script:
  - export CC=gcc-10
  - export CXX=g++-10
  - ldd --version
  - cmake --version
  - cmake
  - make